# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class ChatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PostMessage = channel.unary_unary(
        '/chat.Chat/PostMessage',
        request_serializer=chat__pb2.Message.SerializeToString,
        response_deserializer=chat__pb2.Empty.FromString,
        )
    self.GetMessages = channel.unary_stream(
        '/chat.Chat/GetMessages',
        request_serializer=chat__pb2.Empty.SerializeToString,
        response_deserializer=chat__pb2.Message.FromString,
        )


class ChatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PostMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMessages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PostMessage': grpc.unary_unary_rpc_method_handler(
          servicer.PostMessage,
          request_deserializer=chat__pb2.Message.FromString,
          response_serializer=chat__pb2.Empty.SerializeToString,
      ),
      'GetMessages': grpc.unary_stream_rpc_method_handler(
          servicer.GetMessages,
          request_deserializer=chat__pb2.Empty.FromString,
          response_serializer=chat__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chat.Chat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
