# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fortune_pb2 as fortune__pb2


class FortuneStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCookie = channel.unary_unary(
        '/fortune.Fortune/GetCookie',
        request_serializer=fortune__pb2.Request.SerializeToString,
        response_deserializer=fortune__pb2.Cookie.FromString,
        )


class FortuneServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetCookie(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FortuneServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCookie': grpc.unary_unary_rpc_method_handler(
          servicer.GetCookie,
          request_deserializer=fortune__pb2.Request.FromString,
          response_serializer=fortune__pb2.Cookie.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fortune.Fortune', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
