# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fortune.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fortune.proto',
  package='fortune',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rfortune.proto\x12\x07\x66ortune\"\x1b\n\x07Request\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"\x16\n\x06\x43ookie\x12\x0c\n\x04text\x18\x01 \x01(\t2;\n\x07\x46ortune\x12\x30\n\tGetCookie\x12\x10.fortune.Request\x1a\x0f.fortune.Cookie\"\x00\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='fortune.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='fortune.Request.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=53,
)


_COOKIE = _descriptor.Descriptor(
  name='Cookie',
  full_name='fortune.Cookie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='fortune.Cookie.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Cookie'] = _COOKIE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'fortune_pb2'
  # @@protoc_insertion_point(class_scope:fortune.Request)
  })
_sym_db.RegisterMessage(Request)

Cookie = _reflection.GeneratedProtocolMessageType('Cookie', (_message.Message,), {
  'DESCRIPTOR' : _COOKIE,
  '__module__' : 'fortune_pb2'
  # @@protoc_insertion_point(class_scope:fortune.Cookie)
  })
_sym_db.RegisterMessage(Cookie)



_FORTUNE = _descriptor.ServiceDescriptor(
  name='Fortune',
  full_name='fortune.Fortune',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=79,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCookie',
    full_name='fortune.Fortune.GetCookie',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_COOKIE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FORTUNE)

DESCRIPTOR.services_by_name['Fortune'] = _FORTUNE

# @@protoc_insertion_point(module_scope)
